spring:
  application:
    name: ubajara-api

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5434/ubajara_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}


aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: sa-east-1
  bucket-name: parque-ubajara-fotos

server:
  port: 8080
  servlet:
    context-path: /api/v1
    session:
      persistent: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
