spring:
  application:
    name: ubajara-api

  output:
    ansi:
      enabled: ALWAYS

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Configuração comum de segurança
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        parqueubajara:
          api: info
    org:
      springframework:
        security: info

# Configurações globais que não mudam entre ambientes
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: sa-east-1
  bucket-name: parque-ubajara-fotos
  cloudfront-url: ${CLOUDFRONT_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: false
  api-docs:
    path: /v3/api-docs

server:
  port: 8081
  servlet:
    context-path: /api/v1

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

app:
  frontend:
    redirect-url: ${FRONTEND_REDIRECT_URL:http://localhost:5173/login-success}
    url: {$FRONTEND_URL:localhost:5173}
---
# PERFIL DE DESENVOLVIMENTO (Local)
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/ubajara_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

---
# PERFIL DE PRODUÇÃO 
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false